export const Inputs = [
  {
    key: "1",
    name: "name",
    marginY: 1,
    label: "Nome completo",
    placeholder: "Nome completo",
    width: "77.77%",
    height: 42,
    returnKeyType: "next",
    alignSelf: "center",
    variant: "underlined",
    autoCapitalize: true,
    secury: false,
    keyboardType: "default",
  },
  {
    key: "2",
    name: "cpf",
    marginY: 1,
    label: "CPF",
    placeholder: "CPF",
    width: "77.77%",
    height: 42,
    returnKeyType: "next",
    alignSelf: "center",
    variant: "underlined",
    autoCapitalize: true,
    secury: false,
    keyboardType: "default",
  },
  {
    key: "3",
    name: "date",
    marginY: 1,
    label: "Data de nascimento",
    placeholder: "Data de nascimento",
    width: "77.77%",
    height: 42,
    returnKeyType: "next",
    alignSelf: "center",
    variant: "underlined",
    autoCapitalize: true,
    secury: false,
    keyboardType: "default",
  },

  {
    key: "4",
    name: "phone",
    marginY: 1,
    label: "Telefone",
    placeholder: "Telefone",
    width: "77.77%",
    height: 42,
    returnKeyType: "next",
    alignSelf: "center",
    variant: "underlined",
    autoCapitalize: false,
    secury: false,
    keyboardType: "numeric",
  },
  {
    key: "5",
    name: "email",
    marginY: 1,
    label: "Email",
    placeholder: "Email",
    width: "77.77%",
    height: 42,
    returnKeyType: "next",
    alignSelf: "center",
    variant: "underlined",
    autoCapitalize: false,
    secury: false,
    keyboardType: "email-address",
    isDisabled: true,
  },
  {
    key: "6",
    name: "cep",
    marginY: 1,
    label: "CEP",
    placeholder: "CEP",
    width: "77.77%",
    height: 42,
    returnKeyType: "next",
    alignSelf: "center",
    variant: "underlined",
    autoCapitalize: true,
    secury: false,
    keyboardType: "default",
  },
  {
    key: "7",
    name: "address",
    marginY: 1,
    label: "Endereço",
    placeholder: "Endereço",
    width: "77.77%",
    height: 42,
    returnKeyType: "next",
    alignSelf: "center",
    variant: "underlined",
    autoCapitalize: true,
    secury: false,
    keyboardType: "default",
  },
  {
    key: "8",
    name: "district",
    marginY: 1,
    label: "Bairro",
    placeholder: "Bairro",
    width: "77.77%",
    height: 42,
    returnKeyType: "next",
    alignSelf: "center",
    variant: "underlined",
    autoCapitalize: true,
    secury: false,
    keyboardType: "default",
  },
  {
    key: "9",
    name: "city",
    marginY: 1,
    label: "Cidade",
    placeholder: "Cidade",
    width: "77.77%",
    height: 42,
    returnKeyType: "next",
    alignSelf: "center",
    variant: "underlined",
    autoCapitalize: true,
    secury: false,
    keyboardType: "default",
  },
  {
    key: "10",
    name: "state",
    marginY: 1,
    label: "Estado",
    placeholder: "Estado",
    width: "77.77%",
    height: 42,
    returnKeyType: "next",
    alignSelf: "center",
    variant: "underlined",
    autoCapitalize: true,
    secury: false,
    keyboardType: "default",
  },
  {
    key: "11",
    name: "password",
    marginY: 1,
    placeholder: "********",
    label: "Senha",
    width: "77.77%",
    height: 42,
    returnKeyType: "next",
    alignSelf: "center",
    variant: "underlined",
    autoCapitalize: false,
    secury: true,
  },
  {
    key: "12",
    name: "rpassword",
    placeholder: "********",
    label: "Repita a senha",
    width: "77.77%",
    height: 42,
    returnKeyType: "go",
    alignSelf: "center",
    variant: "underlined",
    autoCapitalize: false,

    secury: true,
  },
];
